### ISSUE TITLE
Coke Oven "disassembling" when unloaded

### ISSUE THREAD

**Issue by Derekcz** [Railcraft/Railcraft#1909]
**Description of the Bug**
Minecraft 1.12.2 / Railcraft 12.0.0
An assembled Coke Oven will turn into Coke Oven Bricks when the chunk its contained within gets unloaded. This means that it can not be interacted with and needs to be re-built.

**To Reproduce**
1. Create Coke Oven
2. Walk far enough for its chunk to unload
3. Return to see the Coke Oven turned back into Coke Oven Bricks

**Expected behavior**
_I expect it to not do that_

**Screenshots & Video**
![is not work lol](https://user-images.githubusercontent.com/36073034/70812973-f89e2580-1dc8-11ea-9ab6-6425689400c2.png)

**Additional context**
The Coke Oven still seems to be functional in this state, when one block is broken and placed again, it becomes a full Oven again and retains its contents, so its not a very destructive bug, mainly annoying.
Luckily I can use the Immersive Engineering Coke Oven as a backup.

**Comment by Dealdion50** [comment]
I am also receiving this bug, however, whenever I try to click on the furnace when it's in this state (if I happen to not notice) it will rearrange my entire inventory visually. If I use InventoryTweaks to sort it it goes back to normal, but it took a while to figure that out and I was stuck with blocks in my armor slots that couldn't be used once removed. My crafting grid is broken even after sorting, requiring a disconnect.

**Comment by CovertJaguar** [comment]
Possibly fixed by b6c7c4b005ca5545371bbf6138ea4ab10e9e070d

**Comment by jimmytrouser** [comment]
This is still happening as of 26/01/2021

3/16/2019  railcraft-12.0.0.jar

**Comment by Mantarri** [comment]
I also am having this bug.
**Forge** 14.23.5.2855
**Railcraft** 12.0.0.
